### ISSUE TITLE
organize first hackathon

### ISSUE THREAD

**Issue by egonw** [cdk/nwo-openscience-2024#1]

**Comment by egonw** [comment]
@Maddocent, may I suggest to have the first hackathon (in the first month of the project) in Maastricht?

**Comment by egonw** [comment]
Planned for April 4-5 in Maastricht (only option where we had a chance).

cc @RvdPloeg

**Comment by egonw** [comment]
Venue: UNS 60, universiteitssingel 60, Maastricht

Hotel options: Amrath (next to the train station) and the NH (next to the MECC). Both have pros and cons.

**Comment by RvdPloeg** [comment]
Hoi Egon,

Met betrekking tot de hackathon. Is het idee om te overnachten in Maastricht? Mocht het zonder overnachting zijn wat is dan de verwachte start en eindtijd?

Om mijn deelname te organiseren heb ik deze informatie nodig.

Groeten en bedankt,

René



Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Egon Willighagen ***@***.***>
Verzonden: Tuesday, March 19, 2024 1:22:22 PM
Aan: cdk/nwo-openscience-2024 ***@***.***>
CC: René van der Ploeg ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [cdk/nwo-openscience-2024] organize first hackathon (Issue #1)

LET OP: Deze e-mail komt van een afzender buiten de HU. Klik niet op links en bijlagen als de afzender niet bekend of vertrouwd is. Caution: This email is from a sender outside HU. Do not click on links and attachments if the sender is not known or trusted.


Planned for April 4-5 in Maastricht (only option where we had a chance).

cc @RvdPloeg<https://github.com/RvdPloeg>

**Comment by egonw** [comment]
> Is het idee om te overnachten in Maastricht?

Ja, de grant heeft daar geld voor gereserveerd.

**Comment by egonw** [comment]
Write up: https://chem-bla-ics.linkedchemistry.info/2024/04/07/cdk2024.html
