### ISSUE TITLE
publish project proposal

### ISSUE THREAD

**Issue by egonw** [cdk/nwo-openscience-2024#21]
@maddocent, our previous NWO Open Science grant got published in RIO Journal: https://doi.org/10.3897/rio.8.e83031 The proposal was published pretty much verbatim of what we submitted.

I like to do that this time again. Is your team okay with that?

**Comment by Maddocent** [comment]
Sure!

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
From: Egon Willighagen ***@***.***>
Sent: Saturday, January 6, 2024 1:03:06 PM
To: cdk/nwo-openscience-2024 ***@***.***>
Cc: Marc Teunis ***@***.***>; Mention ***@***.***>
Subject: [cdk/nwo-openscience-2024] publish project proposal? (Issue #21)

LET OP: Deze e-mail komt van een afzender buiten de HU. Klik niet op links en bijlagen als de afzender niet bekend of vertrouwd is. Caution: This email is from a sender outside HU. Do not click on links and attachments if the sender is not known or trusted.


@Maddocent<https://github.com/Maddocent>, our previous NWO Open Science grant got published in RIO Journal: https://doi.org/10.3897/rio.8.e83031 The proposal was published pretty much verbatim of what we submitted.

I like to do that this time again. Is your team okay with that?

**Comment by egonw** [comment]
Draft here: https://arpha.pensoft.net/preview.php?document_id=24627

**Comment by egonw** [comment]
Submitted for technical review.

**Comment by egonw** [comment]
Published some time ago and blogged about it: https://chem-bla-ics.linkedchemistry.info/2024/05/18/cdk2024-2.html
