### ISSUE TITLE
Set up GitHub Actions for JChemPaint

### ISSUE THREAD

**Issue by egonw** [cdk/nwo-openscience-2024#24]
See also: https://github.com/cdk/nwo-openscience-2024/issues/11

**Comment by jmillanacosta** [comment]
https://github.com/JChemPaint/jchempaint/blob/32864f345046ad25ceb3780b3dced0381790a355/core/src/test/java/org/openscience/cdk/CDKTestCase.java

Build up on this?

**Comment by egonw** [comment]
Added: https://github.com/JChemPaint/jchempaint/actions

The testing is hard, because this needs a running window manager and does not work in a headless environment.
